theme = "bogster"

[editor]
line-number = "relative"
color-modes = true
bufferline = "multiple"

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.soft-wrap]
enable = true

[editor.indent-guides]
render = true
